import { chromium } from "playwright";
import { enterWorkspace } from "./enter.mjs";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: 1440, height: 950 } });
await page.goto("http://localhost:5173/", { waitUntil: "domcontentloaded" });
await enterWorkspace(page);
await page.getByRole("button", { name: "Templates", exact: true }).click();
await page.locator(".overlay").getByTitle(/^Build the box with lid\b/).click();
await page.waitForFunction(() => document.querySelector(".msg.assistant .bubble")?.textContent?.includes("box"), null, { timeout: 120_000 });
await page.waitForTimeout(900);
await page.locator(".viewerCanvas canvas").screenshot({ path: "shot-dims-initial.png" });
await browser.close();
