import { chromium } from "playwright";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: 1440, height: 950 } });
await page.addInitScript(() => localStorage.setItem("moldable_entered", "1"));
await page.goto("http://localhost:5173/", { waitUntil: "domcontentloaded" });
await page.waitForSelector(".topbar", { timeout: 60_000 });
await page.getByRole("button", { name: "Templates", exact: true }).click();
await page.locator(".overlay").getByTitle("Build the coaster template").click();
await page.waitForFunction(() => document.querySelector(".msg.assistant .bubble")?.textContent?.toLowerCase().includes("coaster"), null, { timeout: 120_000 });
await page.waitForTimeout(2500);
await page.getByRole("button", { name: "Templates", exact: true }).click();
await page.waitForTimeout(500);
await page.screenshot({ path: "shot-gallery-new.png" });
await page.locator(".overlay button.x, .overlay .x").first().click().catch(() => page.mouse.click(30, 500));
await page.waitForTimeout(300);
await page.getByRole("button", { name: "Library", exact: true }).click();
await page.waitForTimeout(700);
await page.screenshot({ path: "shot-library-new.png" });
await browser.close();
console.log("done");
